config/routes.rb
Twitterclone::Application.routes.draw do
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", as: "logout"

  resources :users
  resources :sessions
  resources :tweets
  
  root "users#index"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tweets
	has_many :followers
	has_many :followings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def index

	end

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:info] = "Logged in!"
			redirect_to root_url
		else
			flash[:info] = "Invalid email or password"
			render "new"
		end
	end

	def destroy 
		session[:user_id] = nil
    	flash[:info] = "Logged out successfully!"
    	redirect_to root_path
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	def index
		@tweets = Tweet.all
	end

	def new
		@tweet = Tweet.new
	end

	def create
		@tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    @tweet.save!
    flash[:info] = "Added a new tweet!"
    redirect_to tweet_path(:id)
	end

	def show
		 @tweet = Tweet.find(session[:user_id])
	end
	

	private

	def tweet_params
		params.require(:tweet).permit(:body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@tweets = @user.tweets
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterclone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class='navbar navbar-default'>
  <a class='navbar-brand' href='/'>TwitterClone</a>
  <ul class='nav navbar-nav'>
	<% if current_user %>
	  <%=  "You are logged in as #{current_user.username}" %>
	  <li><%= link_to "Logout", logout_path %></li>
	<% else %>
	  <li><%= link_to "Login", login_path %></li>
	  <li><%= link_to "Register", new_user_path %></li>
	<% end %>
  </ul>
</nav>

<div class='container'>

  <% if flash[:info] %>
    <div class='alert alert-info'>
      <%= flash[:info] %>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/tweets/new.html.erb
<h2>Enter a Tweet:</h2>

<% if current_user %>
	<%= simple_form_for @tweet do |f| %>
		<%= f.input :body %>
	<br>
		<%= f.submit "Post Tweet!", class: 'btn btn-primary' %>
		<%= link_to "Cancel", root_url, class: 'btn btn-primary' %>
	<% end %>
<% end %>

app/views/tweets/show.html.erb
<h2><%= current_user.first_name %>'s Tweets</h2>


<ul>
	<% current_user.tweets.each do |tweet| %>
		<li><%= tweet.body %></li>
	<% end %>
</ul>

app/views/users/index.html.erb
<h1>TwitterClone Start</h1>


<%= link_to "New Tweet", new_tweet_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= simple_form_for @user do |f| %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :email %>
	<%= f.input :username %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>
	<br>
	<%= f.submit "Register", class: 'btn btn-primary'%>
	<%= link_to "Cancel", root_url, class: 'btn btn-primary' %>
	<br>
<% end %>